export const GET_TRACK_BY_ID = 'GET_TRACK_BY_ID';
export const GET_TRACK_BY_ID_SUCCESS = 'GET_TRACK_BY_ID_SUCCESS';
export const GET_TRACK_BY_ID_FAILURE = 'GET_TRACK_BY_ID_FAILURE';

export const GET_TRACKS_BY_ARTIST = 'GET_TRACKS_BY_ARTIST';
export const GET_TRACKS_BY_ARTIST_SUCCESS = 'GET_TRACKS_BY_ARTIST_SUCCESS';
export const GET_TRACKS_BY_ARTIST_FAILURE = 'GET_TRACKS_BY_ARTIST_FAILURE';

export const RESET_TRACKS_LIST = 'RESET_TRACKS_LIST';
