export const ADD_FAVORITE = 'ADD_FAVORITE';

export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';

export const GET_FAV_TRACK_BY_ID = 'GET_FAV_TRACK_BY_ID';
export const GET_FAV_TRACK_BY_ID_SUCCESS = 'GET_FAV_TRACK_BY_ID_SUCCESS';
export const GET_FAV_TRACK_BY_ID_FAILURE = 'GET_FAV_TRACK_BY_ID_FAILURE';

export const RESET_FAVORITES_LIST = 'RESET_FAVORITES_LIST';
